version: "1.0.0"
hooks:
  - name: general
    rules:
      - type: commit
        conditions:
        - type: length
          condition: lt 120
        - type: pattern
          condition: (?m)^(?P<type>build|ci|chore|docs|feat|fix|perf|refactor|style|test)(?P<scope>\([a-z]+\))*:\s(?P<subject>[[:word:]\s./'-]+)$
          skip: Initial commit
        - type: email
          condition: (?m)^[a-zA-Z.\-]+@gmail.com$
          ignore: true
      - type: security
        conditions:
        - type: secret
          skip: docs/.*|.*.json|test/.*
