run:
  tests: false

linters:
  enable-all: true
  disable:
    - exhaustive
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - gosec
    - lll
    - maligned
    - nestif
    - nlreturn
    - noctx
    - scopelint
    - wsl
