auth_basic_token: WATCHDOG_AUTH_BASIC_TOKEN
banner: true
cache_directory: /opt/watchdog/repositories
contact: Habib MAALEM <habib.maalem@gmail.com>
debug: true
default_handlers:
  file:
    description: File default handler
    type: file
    conditions:
    - type: size
      condition: lt 1mb
  security:
    description: Security default handler
    disabled: false
    type: security
    conditions:
    - type: secret
      ignore: true
      skip: .*.go|CONTRIBUTING.md|docs/.*|test/.*|.*.min.js
docs_link: https://groupe-edf.github.io/watchdog/docs/
# Prefix to have custom error messages appear in GitLab’s UI
# when the commit is declined or an error occurs during the Git hook
error_message_prefix: "GL-HOOK-ERR: "
hook_file:
hook_input:
hook_type:
logs_level: info
logs_format: json
logs_path: /var/log/watchdog/watchdog.log
max_workers: 10
output:
output_format: text
plugins_directory:
profile: false
security:
  merge_rules: true
  # reveal_secrets < 0  hide secrets
  # reveal_secrets = 0  reveal full secrets
  # reveal_secrets > 0  partial reveal "x" characters from secrets
  reveal_secrets: 5
  rules:
  - description: GOOGLE_API_KEY
    regexp: AIza[0-9A-Za-z\\-_]{35}
    tags: [key, google]
