# credentials to be used to fetch git repositories
auth_basic_token:
# show or hide watchdog banner
banner: true
# cache directory for git repositories
cache_directory: /opt/watchdog/repositories
contact: Habib MAALEM <habib.maalem@gmail.com>
# link to watchdog documentation
docs_link: https://groupe-edf.github.io/watchdog/docs/
# Prefix to have custom error messages appear in GitLab’s UI
# when the commit is declined or an error occurs during the Git hook
error_message_prefix: "GL-HOOK-ERR: "
# default handlers executed every time analysis is runned
# see https://groupe-edf.github.io/watchdog/docs/handlers/
handlers:
  file:
    description: File default handler
    type: file
    conditions:
    - type: size
      condition: lt 1mb
  security:
    description: Security default handler
    disabled: false
    type: security
    conditions:
    - type: secret
      ignore: true
      skip: .*.go|CONTRIBUTING.md|docs/.*|test/.*|.*.min.js
hook_file:
hook_input:
hook_type:
logs:
  level: info
  format: json
  path: /var/log/watchdog/watchdog.log
# number of cocurrent worker used to run analysis
concurrent: 4
# output file for analysis report
output:
# report format
output_format: text
# coming soon
plugins_directory:
# enable or disable profiling, for development purpose
profile: false
# security options
security:
  # override or not default security rules
  merge_rules: false
  # reveal_secrets < 0  reveal full secrets
  # reveal_secrets = 0  hide secrets
  # reveal_secrets > 0  partial reveal "N" characters from secrets
  reveal_secrets: 4
  # security rules
  rules:
  - description: AWS_ACCESS_KEY
    regexp: (A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}
    severity: MAJOR
    tags: ["cloud", "aws"]
  - description: ASYMMETRIC_PRIVATE_KEY
    regexp: (\-){5}BEGIN[[:blank:]]*?(RSA|OPENSSH|DSA|EC|PGP)?[[:blank:]]*?PRIVATE[[:blank:]]KEY[[:blank:]]*?(BLOCK)?(\-){5}.*
    severity: MAJOR
    tags: ["key", "certificates"]
  - description: CONNECTION_STRING
    regexp: (?i)(?P<scheme>[a-z0-9+-.]{3,30}://)?[0-9a-z-]{3,30}:(?P<secret>[a-zA-Z0-9!?$)(.=<>\/%@#*&{}_^+-]{6,45})@(?P<host>[0-9a-z-.]{1,50})(?::(?P<port>[0-9]{1,5}))?]?
    severity: MAJOR
  - description: PASSWORD_XML
    file: (?i)(.*.xml)$
    regexp: (?i)<(?:(?:pass(?:w(?:or)?d)?)|(?:p(?:s)?w(?:r)?d)|secret)>(?P<secret>.{5,256})</(?:(?:pass(?:w(?:or)?d)?)|(?:p(?:s)?w(?:r)?d)|secret)>
    severity: MAJOR
  - description: SECRET_KEY
    regexp: (?im)(?:(?:a(?:ws|ccess|p(?:i|p(?:lication)?)))|private|se(?:nsitive|cret))?[[:space:]_-]?(?:key|token)[[:space:]]{0,20}[=:]{1,2}[[:space:]]{0,20}['\"]?(?P<secret>[a-zA-Z0-9!?$)(.=<>\/%@#*&{}_^+-]{6,45})(?:[[:space:];'\",]|$)
    severity: MAJOR
    tags: ["token"]
server_url: http://localhost:3001
server_token: GSHMG1A56JWNRX29YXE1IJQ0064QCXRL
server:
  database:
    bolt:
      path: ""
    driver: postgres
    postgres:
      host: localhost
      name: watchdog
      password: watchdog
      port: 5432
      username: watchdog
  ldap:
  - attributes:
      username: uid
      email: mail
      name: cn
      first_name: givenName
      last_name: sn
    bind_dn: cn=watchdog,dc=example,dc=org
    bind_password: watchdog
    host: localhost
    label: Primary LDAP
    port: 1389
    search_base_dns: dc=example,dc=org
    search_filter: (objectClass=*)
    uid: uid
    use_ssl: false
  listen_address: :3001
  oauth_providers:
    - application_id: ""
      application_secret: ""
      args: []
      name: oauth_gitlab
    - application_id: ""
      application_secret: ""
      args: []
      name: oauth_github
  profile: true
  security:
    master_key: secret
  static:
    routes:
    - /integrations
    - /issues
    - /leaks
    - /policies
    - /profile
    - /rules
    - /repositories
    - /settings
    - /users
  storage:
    directory: storage
    driver: local
