name: golangci-lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      ## Checks out our code locally so we can work with the files
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      ## Lint code
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
